name: C
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
    name: ${{ matrix.compiler }} on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      env:
        CC: ${{ matrix.compiler }}
      run: make

    - name: Install Testsuite dependencies (ubuntu)
      if: matrix.operating-system == 'ubuntu-latest'
      run: sudo apt-get install libav-tools

    - name: Install Testsuite dependencies (macos)
      if: matrix.operating-system == 'macos-latest'
      run: brew install libav

    - name: Testsuite
      env:
        CC: ${{ matrix.compiler }}
      run: make test
