name: C
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]
    name: ${{ matrix.compiler }} on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      env:
        CC: ${{ matrix.compiler }}
      run: make
